#!/usr/bin/env ruby

require '/opt/elasticbeanstalk/support/get_envvars'

if __FILE__ == $0
    env_file = '/opt/elasticbeanstalk/support/envvars'
    env_vars = get_env_vars

    str = ''
    env_vars.each do |key, value|
        new_key = key.gsub(/\s/, '_')
        str << "export #{new_key}=\"#{value}\"\n"
    end
    
    File.open(env_file, 'w') { |f| f.write(str) }

    fastcgi_params_file = '/etc/nginx/fastcgi_params'
    env_vars = get_env_vars

    str = ''
    env_vars.each do |key, value|
        new_key = key.gsub(/\s/, '_')
        str << "fastcgi_param #{new_key} \"#{value}\";\n"
    end

    File.open(fastcgi_params_file, 'a') { |f| f.write(str) }
end
